apiVersion: v1
kind: PersistentVolume
metadata:
  name: repo-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  # for single node cluster
  hostPath:
    path: "/rpm"
    type: DirectoryOrCreate