apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-pvc
  namespace: rpm-repo
spec:
  # storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
