apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80  # The port on which the Service will listen
      targetPort: 80  # The port to which the traffic will be forwarded in the pods
      nodePort: 30050
  type: NodePort