apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world
spec:
  replicas: {{ .Values.numberOfReplicas }}
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        {{ include "myLabels" .  | indent 8}}
    spec:
      containers:
      - name: hello-world
        image: {{ .Values.resistry.repoName | lower | default "praveen21b" }}/{{ .Values.resistry.image.name }}:{{ if .Values.resistry.image.tag }}dev{{ else }}prod{{ end }}
        ports:
        - name: http
          containerPort: 80
          targetPort: 80
      
