apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80  # The port on which the Service will listen
      targetPort: 80  # The port to which the traffic will be forwarded in the pods
      nodePort: 30050
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world
spec:
  replicas: {{ .Values.numberOfReplicas }}
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: {{ lower .Values.resistry.repoName }}/{{ .Values.resistry.image.name }}:{{ .Values.resistry.image.tag }}
        ports:
        - name: http
          containerPort: 80
          targetPort: 80